// Copyright The palan Authors
// SPDX-License-Identifier: Apache-2.0

package signing

import (
	"crypto"
	"crypto/x509"
	"encoding/pem"
	"fmt"

	"github.com/secure-systems-lab/go-securesystemslib/encrypted"
	"github.com/sigstore/sigstore/pkg/cryptoutils"
	"github.com/sigstore/sigstore/pkg/signature"
)

// cosign's encrypted private key PEM types (current and legacy).
const (
	cosignPEMType       = "ENCRYPTED SIGSTORE PRIVATE KEY"
	cosignLegacyPEMType = "ENCRYPTED COSIGN PRIVATE KEY"
)

// PassFunc supplies the key password when needed (may be nil for
// unencrypted keys).
type PassFunc func() ([]byte, error)

// LoadSigner builds a signer from a PEM private key: either a cosign
// encrypted key (scrypt + NaCl secretbox, as generated by
// `cosign generate-key-pair`) or a plain PKCS#8/EC/PKCS#1 PEM.
func LoadSigner(pemBytes []byte, pass PassFunc) (signature.Signer, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, fmt.Errorf("no PEM block in key file")
	}

	if block.Type == cosignPEMType || block.Type == cosignLegacyPEMType {
		if pass == nil {
			return nil, fmt.Errorf("key is encrypted; a password is required (COSIGN_PASSWORD or prompt)")
		}
		pw, err := pass()
		if err != nil {
			return nil, err
		}
		der, err := encrypted.Decrypt(block.Bytes, pw)
		if err != nil {
			return nil, fmt.Errorf("decrypting key (wrong password?): %w", err)
		}
		priv, err := x509.ParsePKCS8PrivateKey(der)
		if err != nil {
			return nil, fmt.Errorf("parsing decrypted key: %w", err)
		}
		return signature.LoadSignerVerifier(priv, crypto.SHA256)
	}

	priv, err := cryptoutils.UnmarshalPEMToPrivateKey(pemBytes, nil)
	if err != nil {
		return nil, fmt.Errorf("parsing private key: %w", err)
	}
	return signature.LoadSignerVerifier(priv, crypto.SHA256)
}
